In [1]:
import numpy as np 
np.random.seed(2023)

In [69]:
ratings = np.genfromtxt('ratings.dat',delimiter='::',dtype=int)
users = np.genfromtxt('users.dat',delimiter='::', dtype='str')
movies = np.genfromtxt('movies.dat',delimiter='::',dtype='str')

In [70]:
print(ratings)
print(users)
print(movies)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
[['1' 'F' '1' '10' '48067']
 ['2' 'M' '56' '16' '70072']
 ['3' 'M' '25' '15' '55117']
 ...
 ['6038' 'F' '56' '1' '14706']
 ['6039' 'F' '45' '0' '01060']
 ['6040' 'M' '25' '6' '11106']]
[['1' 'Toy Story (1995)' "Animation|Children's|Comedy"]
 ['2' 'Jumanji (1995)' "Adventure|Children's|Fantasy"]
 ['3' 'Grumpier Old Men (1995)' 'Comedy|Romance']
 ...
 ['3950' 'Tigerland (2000)' 'Drama']
 ['3951' 'Two Family House (2000)' 'Drama']
 ['3952' 'Contender, The (2000)' 'Drama|Thriller']]


In [33]:
model = 4*np.random.rand(5) + 1

In [83]:
def split(data):
    """
    This function shuffles the rows the data array to randomize the data, and then splits it in to five seperate arrays
    """
    np.random.shuffle(data)
    split_data = np.array_split(data,5)
    return split_data

ratings_split = split(ratings)
users_split = split(users)
movies_split = split(movies)

[array([[     5463,       720,         3, 959900451],
       [     3620,      3185,         4, 966577306],
       [     3729,      2174,         3, 966575853],
       ...,
       [     2842,       866,         4, 972548608],
       [     4407,      3821,         1, 965154877],
       [     2076,      2572,         3, 975381096]]), array([[      991,      1230,         3, 975087748],
       [     5172,      1244,         4, 995327883],
       [     5284,       527,         4, 961097816],
       ...,
       [     5605,       938,         3, 959570813],
       [     5806,      2248,         4, 957986553],
       [     4150,      1253,         4, 965343775]]), array([[     1943,      3175,         4, 974692989],
       [     1383,       454,         4, 976148617],
       [     3320,         2,         4, 968522205],
       ...,
       [     4421,      2617,         4, 965118603],
       [      173,       922,         5, 990547981],
       [     3189,      2136,         4, 969862790]]), arr